/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface DailyReward {
  'stakedMaturityE8s' : E8s,
  'unstakedMaturityE8s' : E8s,
  'autoStakeMaturity' : boolean,
  'timestamp' : Timestamp,
  'neuronId' : NeuronId,
  'deltaE8s' : DeltaE8s,
  'eventType' : EventType,
}
export type DeltaE8s = bigint;
export type E8s = bigint;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type EventType = { 'normalGrowth' : null } |
  { 'firstReading' : null } |
  { 'disburseOrSpawn' : null };
export interface HistoricalEntry {
  'stakedMaturityE8s' : E8s,
  'unstakedMaturityE8s' : E8s,
  'timestamp' : Timestamp,
}
export interface MonthlyBreakdown {
  'month' : bigint,
  'totalDeltaE8s' : bigint,
  'year' : bigint,
  'readingCount' : bigint,
}
export interface Neuron {
  'id' : NeuronId,
  'dissolveDelaySeconds' : bigint,
  'ownerId' : Principal,
  'name' : string,
  'stakedE8s' : E8s,
  'initialStakeE8s' : E8s,
  'startDate' : Timestamp,
}
export type NeuronId = bigint;
export interface NeuronStats {
  'averageDailyRewardE8s' : bigint,
  'totalRewardsE8s' : bigint,
  'percentageReturn' : number,
  'neuronId' : NeuronId,
  'monthly' : Array<MonthlyBreakdown>,
}
export interface PortfolioStats {
  'totalRewardsE8s' : bigint,
  'totalStakedE8s' : E8s,
  'percentageReturn' : number,
  'neuronCount' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface SyncResult {
  'status' : SyncStatus,
  'maturityE8s' : [] | [bigint],
  'lastSyncError' : [] | [string],
  'stakedE8s' : [] | [bigint],
  'neuronId' : NeuronId,
}
export type SyncStatus = { 'hotkeyRequired' : null } |
  { 'neverSynced' : null } |
  { 'failed' : null } |
  { 'synced' : null };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__neurons' : ActorMethod<[], any>,
  '__rewards' : ActorMethod<[], any>,
  '__syncErrors' : ActorMethod<[], any>,
  '__syncStatuses' : ActorMethod<[], any>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addNeuron' : ActorMethod<
    [NeuronId, string, bigint, bigint, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNeuronStats' : ActorMethod<[NeuronId], NeuronStats>,
  'getPortfolioStats' : ActorMethod<[], PortfolioStats>,
  'getRewardHistory' : ActorMethod<[NeuronId], Array<DailyReward>>,
  'getSyncError' : ActorMethod<[NeuronId], [] | [string]>,
  'getSyncStatus' : ActorMethod<[NeuronId], SyncStatus>,
  'importHistoricalData' : ActorMethod<
    [NeuronId, Array<HistoricalEntry>],
    undefined
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyNeurons' : ActorMethod<[], Array<Neuron>>,
  'recordSnapshot' : ActorMethod<
    [NeuronId, bigint, bigint, boolean],
    DailyReward
  >,
  'removeNeuron' : ActorMethod<[NeuronId], undefined>,
  'schema' : ActorMethod<[], string>,
  'syncAllMyNeurons' : ActorMethod<[], Array<SyncResult>>,
  'syncNeuron' : ActorMethod<[NeuronId], SyncResult>,
  'updateNeuron' : ActorMethod<[Neuron], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];