/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface DailyReward {
  'stakedMaturityE8s' : E8s,
  'unstakedMaturityE8s' : E8s,
  'stakeDeltaE8s' : E8s,
  'autoStakeMaturity' : boolean,
  'timestamp' : Timestamp,
  'neuronId' : NeuronId,
  'deltaE8s' : DeltaE8s,
  'eventType' : EventType,
}
export type DeltaE8s = bigint;
export type E8s = bigint;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type EventType = { 'mergedToStake' : null } |
  { 'normalGrowth' : null } |
  { 'firstReading' : null } |
  { 'externalTopUp' : null } |
  { 'disburseOrSpawn' : null };
export interface HistoricalEntry {
  'stakedMaturityE8s' : E8s,
  'unstakedMaturityE8s' : E8s,
  'timestamp' : Timestamp,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface MonthlyBreakdown {
  'month' : bigint,
  'totalDeltaE8s' : bigint,
  'year' : bigint,
  'readingCount' : bigint,
  'momDeltaE8s' : bigint,
}
export interface Neuron {
  'id' : NeuronId,
  'dissolveDelaySeconds' : bigint,
  'ownerId' : Principal,
  'name' : string,
  'stakedE8s' : E8s,
  'initialStakeE8s' : E8s,
  'startDate' : Timestamp,
}
export type NeuronId = bigint;
export interface NeuronStats {
  'averageDailyRewardE8s' : bigint,
  'totalRewardsE8s' : bigint,
  'totalCapitalContributedE8s' : E8s,
  'apy30d' : number,
  'percentageReturn' : number,
  'neuronId' : NeuronId,
  'monthly' : Array<MonthlyBreakdown>,
  'overallReturnPct' : number,
}
export interface PortfolioStats {
  'totalMaturityE8s' : bigint,
  'totalRewardsThisMonthE8s' : bigint,
  'totalRewardsE8s' : bigint,
  'blendedApy' : number,
  'totalStakedE8s' : E8s,
  'totalCapitalContributedE8s' : E8s,
  'percentageReturn' : number,
  'neuronCount' : bigint,
}
export interface PriceSnapshot {
  'pln' : number,
  'usd' : number,
  'timestamp' : bigint,
  'cached' : boolean,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface SyncResult {
  'status' : SyncStatus,
  'maturityE8s' : [] | [bigint],
  'lastSyncError' : [] | [string],
  'stakedE8s' : [] | [bigint],
  'neuronId' : NeuronId,
}
export type SyncStatus = { 'hotkeyRequired' : null } |
  { 'neverSynced' : null } |
  { 'failed' : null } |
  { 'synced' : null };
export type TimerId = bigint;
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type WtnEventType = { 'firstReading' : null } |
  { 'capitalAdded' : null } |
  { 'withdrawal' : null } |
  { 'organicGrowth' : null };
export interface WtnHistoricalEntry {
  'date' : Timestamp,
  'redeemableIcpValue' : number,
  'nicpHeld' : number,
  'totalIcpPaid' : number,
}
export interface WtnPosition {
  'id' : WtnPositionId,
  'ownerId' : Principal,
  'name' : string,
  'startDate' : Timestamp,
}
export type WtnPositionId = bigint;
export interface WtnSnapshot {
  'date' : Timestamp,
  'positionId' : WtnPositionId,
  'redeemableIcpValue' : number,
  'nicpHeld' : number,
  'eventType' : WtnEventType,
  'totalIcpPaid' : number,
}
export interface WtnStats {
  'percentReturn' : number,
  'totalCapitalContributed' : number,
  'totalEarned' : number,
  'positionId' : WtnPositionId,
  'redeemableIcpValue' : number,
  'totalWithdrawn' : number,
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__neurons' : ActorMethod<[], any>,
  '__nextWtnPositionId' : ActorMethod<[], any>,
  '__priceCache' : ActorMethod<[], any>,
  '__rewards' : ActorMethod<[], any>,
  '__syncErrors' : ActorMethod<[], any>,
  '__syncStatuses' : ActorMethod<[], any>,
  '__wtnPositions' : ActorMethod<
    [[] | [WtnPositionId], [] | [bigint]],
    Array<[WtnPositionId, WtnPosition]>
  >,
  '__wtnSnapshots' : ActorMethod<[], any>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addNeuron' : ActorMethod<
    [NeuronId, string, bigint, bigint, bigint],
    undefined
  >,
  'addWtnPosition' : ActorMethod<[string, bigint], WtnPosition>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteSnapshot' : ActorMethod<[NeuronId, bigint], undefined>,
  'deleteWtnSnapshot' : ActorMethod<[WtnPositionId, bigint], undefined>,
  'editSnapshot' : ActorMethod<[NeuronId, bigint, bigint, bigint], undefined>,
  'editWtnSnapshot' : ActorMethod<
    [WtnPositionId, bigint, bigint, number, number, number],
    undefined
  >,
  'execute' : ActorMethod<[string], Result>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentIcpPrice' : ActorMethod<[], PriceSnapshot>,
  'getHistoricalIcpPrice' : ActorMethod<[string], PriceSnapshot>,
  'getNeuronStats' : ActorMethod<[NeuronId], NeuronStats>,
  'getPortfolioStats' : ActorMethod<[], PortfolioStats>,
  'getRewardHistory' : ActorMethod<[NeuronId], Array<DailyReward>>,
  'getSyncError' : ActorMethod<[NeuronId], [] | [string]>,
  'getSyncStatus' : ActorMethod<[NeuronId], SyncStatus>,
  'getWtnPosition' : ActorMethod<[WtnPositionId], [] | [WtnPosition]>,
  'getWtnSnapshots' : ActorMethod<[WtnPositionId], Array<WtnSnapshot>>,
  'getWtnStats' : ActorMethod<[WtnPositionId], WtnStats>,
  'importHistoricalData' : ActorMethod<
    [NeuronId, Array<HistoricalEntry>],
    undefined
  >,
  'importWtnHistoricalData' : ActorMethod<
    [WtnPositionId, Array<WtnHistoricalEntry>],
    undefined
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyNeurons' : ActorMethod<[], Array<Neuron>>,
  'listMyWtnPositions' : ActorMethod<[], Array<WtnPosition>>,
  'recordSnapshot' : ActorMethod<
    [NeuronId, bigint, bigint, boolean],
    DailyReward
  >,
  'recordWtnSnapshot' : ActorMethod<
    [WtnPositionId, bigint, number, number, number],
    WtnSnapshot
  >,
  'removeNeuron' : ActorMethod<[NeuronId], undefined>,
  'removeWtnPosition' : ActorMethod<[WtnPositionId], undefined>,
  /**
   * / Schedule the next daily sync at 18:01 Europe/Warsaw. Recomputes the
   * / target on every call so DST transitions do not cause drift. After the
   * / sync runs, reschedules for the following 18:01 Warsaw.
   * /
   * / `Timer.setTimer<system>` requires the `<system>` capability, which is
   * / available in `shared` functions and async callbacks but NOT in a plain
   * / actor `func` or a transient-let initializer. This function is therefore
   * / only ever called from two system-capable contexts: (1) the
   * / `public shared func startDailySync()` below, and (2) the async timer
   * / callback passed to `Timer.setTimer` (which itself has the system
   * / capability, so rescheduling works). It must NOT be called from a plain
   * / transient let or a non-shared private func.
   */
  'scheduleNextSync' : ActorMethod<[], TimerId>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Install the daily sync timer on first call. Public shared functions run
   * / in an async context that has the `<system>` capability, so
   * / `scheduleNextSync()` (which calls `Timer.setTimer<system>`) is valid
   * / here. Idempotent: subsequent calls are no-ops once the timer is running
   * / (the timer reschedules itself from its own async callback, which also
   * / has the system capability).
   */
  'startDailySync' : ActorMethod<[], undefined>,
  'syncAllMyNeurons' : ActorMethod<[], Array<SyncResult>>,
  'syncNeuron' : ActorMethod<[NeuronId], SyncResult>,
  /**
   * / IC HTTP outcall transform callback. Required by the IC HTTP outcall
   * / protocol: it must be a public `query` function on the actor and strips
   * / response headers so the response body is the only thing that survives
   * / into consensus. Passed to PricesLib functions and the PricesApi mixin.
   */
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateNeuron' : ActorMethod<[Neuron], undefined>,
  'updateWtnPosition' : ActorMethod<[WtnPosition], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];