/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const NeuronId = IDL.Nat64;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const MonthlyBreakdown = IDL.Record({
  'month' : IDL.Nat,
  'totalDeltaE8s' : IDL.Int,
  'year' : IDL.Nat,
  'readingCount' : IDL.Nat,
});
export const NeuronStats = IDL.Record({
  'averageDailyRewardE8s' : IDL.Int,
  'totalRewardsE8s' : IDL.Int,
  'percentageReturn' : IDL.Float64,
  'neuronId' : NeuronId,
  'monthly' : IDL.Vec(MonthlyBreakdown),
});
export const E8s = IDL.Nat64;
export const PortfolioStats = IDL.Record({
  'totalRewardsE8s' : IDL.Int,
  'totalStakedE8s' : E8s,
  'percentageReturn' : IDL.Float64,
  'neuronCount' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const DeltaE8s = IDL.Int;
export const EventType = IDL.Variant({
  'normalGrowth' : IDL.Null,
  'firstReading' : IDL.Null,
  'disburseOrSpawn' : IDL.Null,
});
export const DailyReward = IDL.Record({
  'stakedMaturityE8s' : E8s,
  'unstakedMaturityE8s' : E8s,
  'autoStakeMaturity' : IDL.Bool,
  'timestamp' : Timestamp,
  'neuronId' : NeuronId,
  'deltaE8s' : DeltaE8s,
  'eventType' : EventType,
});
export const SyncStatus = IDL.Variant({
  'hotkeyRequired' : IDL.Null,
  'neverSynced' : IDL.Null,
  'failed' : IDL.Null,
  'synced' : IDL.Null,
});
export const HistoricalEntry = IDL.Record({
  'stakedMaturityE8s' : E8s,
  'unstakedMaturityE8s' : E8s,
  'timestamp' : Timestamp,
});
export const Neuron = IDL.Record({
  'id' : NeuronId,
  'dissolveDelaySeconds' : IDL.Nat64,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'stakedE8s' : E8s,
  'initialStakeE8s' : E8s,
  'startDate' : Timestamp,
});
export const SyncResult = IDL.Record({
  'status' : SyncStatus,
  'maturityE8s' : IDL.Opt(IDL.Nat64),
  'lastSyncError' : IDL.Opt(IDL.Text),
  'stakedE8s' : IDL.Opt(IDL.Nat64),
  'neuronId' : NeuronId,
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__neurons' : IDL.Func([], [IDL.Reserved], ['query']),
  '__rewards' : IDL.Func([], [IDL.Reserved], ['query']),
  '__syncErrors' : IDL.Func([], [IDL.Reserved], ['query']),
  '__syncStatuses' : IDL.Func([], [IDL.Reserved], ['query']),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addNeuron' : IDL.Func(
      [NeuronId, IDL.Text, IDL.Int, IDL.Nat64, IDL.Nat64],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNeuronStats' : IDL.Func([NeuronId], [NeuronStats], []),
  'getPortfolioStats' : IDL.Func([], [PortfolioStats], []),
  'getRewardHistory' : IDL.Func([NeuronId], [IDL.Vec(DailyReward)], []),
  'getSyncError' : IDL.Func([NeuronId], [IDL.Opt(IDL.Text)], []),
  'getSyncStatus' : IDL.Func([NeuronId], [SyncStatus], []),
  'importHistoricalData' : IDL.Func(
      [NeuronId, IDL.Vec(HistoricalEntry)],
      [],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyNeurons' : IDL.Func([], [IDL.Vec(Neuron)], []),
  'recordSnapshot' : IDL.Func(
      [NeuronId, IDL.Nat64, IDL.Nat64, IDL.Bool],
      [DailyReward],
      [],
    ),
  'removeNeuron' : IDL.Func([NeuronId], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'syncAllMyNeurons' : IDL.Func([], [IDL.Vec(SyncResult)], []),
  'syncNeuron' : IDL.Func([NeuronId], [SyncResult], []),
  'updateNeuron' : IDL.Func([Neuron], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const NeuronId = IDL.Nat64;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const MonthlyBreakdown = IDL.Record({
    'month' : IDL.Nat,
    'totalDeltaE8s' : IDL.Int,
    'year' : IDL.Nat,
    'readingCount' : IDL.Nat,
  });
  const NeuronStats = IDL.Record({
    'averageDailyRewardE8s' : IDL.Int,
    'totalRewardsE8s' : IDL.Int,
    'percentageReturn' : IDL.Float64,
    'neuronId' : NeuronId,
    'monthly' : IDL.Vec(MonthlyBreakdown),
  });
  const E8s = IDL.Nat64;
  const PortfolioStats = IDL.Record({
    'totalRewardsE8s' : IDL.Int,
    'totalStakedE8s' : E8s,
    'percentageReturn' : IDL.Float64,
    'neuronCount' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const DeltaE8s = IDL.Int;
  const EventType = IDL.Variant({
    'normalGrowth' : IDL.Null,
    'firstReading' : IDL.Null,
    'disburseOrSpawn' : IDL.Null,
  });
  const DailyReward = IDL.Record({
    'stakedMaturityE8s' : E8s,
    'unstakedMaturityE8s' : E8s,
    'autoStakeMaturity' : IDL.Bool,
    'timestamp' : Timestamp,
    'neuronId' : NeuronId,
    'deltaE8s' : DeltaE8s,
    'eventType' : EventType,
  });
  const SyncStatus = IDL.Variant({
    'hotkeyRequired' : IDL.Null,
    'neverSynced' : IDL.Null,
    'failed' : IDL.Null,
    'synced' : IDL.Null,
  });
  const HistoricalEntry = IDL.Record({
    'stakedMaturityE8s' : E8s,
    'unstakedMaturityE8s' : E8s,
    'timestamp' : Timestamp,
  });
  const Neuron = IDL.Record({
    'id' : NeuronId,
    'dissolveDelaySeconds' : IDL.Nat64,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'stakedE8s' : E8s,
    'initialStakeE8s' : E8s,
    'startDate' : Timestamp,
  });
  const SyncResult = IDL.Record({
    'status' : SyncStatus,
    'maturityE8s' : IDL.Opt(IDL.Nat64),
    'lastSyncError' : IDL.Opt(IDL.Text),
    'stakedE8s' : IDL.Opt(IDL.Nat64),
    'neuronId' : NeuronId,
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__neurons' : IDL.Func([], [IDL.Reserved], ['query']),
    '__rewards' : IDL.Func([], [IDL.Reserved], ['query']),
    '__syncErrors' : IDL.Func([], [IDL.Reserved], ['query']),
    '__syncStatuses' : IDL.Func([], [IDL.Reserved], ['query']),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addNeuron' : IDL.Func(
        [NeuronId, IDL.Text, IDL.Int, IDL.Nat64, IDL.Nat64],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNeuronStats' : IDL.Func([NeuronId], [NeuronStats], []),
    'getPortfolioStats' : IDL.Func([], [PortfolioStats], []),
    'getRewardHistory' : IDL.Func([NeuronId], [IDL.Vec(DailyReward)], []),
    'getSyncError' : IDL.Func([NeuronId], [IDL.Opt(IDL.Text)], []),
    'getSyncStatus' : IDL.Func([NeuronId], [SyncStatus], []),
    'importHistoricalData' : IDL.Func(
        [NeuronId, IDL.Vec(HistoricalEntry)],
        [],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyNeurons' : IDL.Func([], [IDL.Vec(Neuron)], []),
    'recordSnapshot' : IDL.Func(
        [NeuronId, IDL.Nat64, IDL.Nat64, IDL.Bool],
        [DailyReward],
        [],
      ),
    'removeNeuron' : IDL.Func([NeuronId], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'syncAllMyNeurons' : IDL.Func([], [IDL.Vec(SyncResult)], []),
    'syncNeuron' : IDL.Func([NeuronId], [SyncResult], []),
    'updateNeuron' : IDL.Func([Neuron], [], []),
  });
};

export const init = ({ IDL }) => { return []; };