/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface WtnPosition {
    id: WtnPositionId;
    ownerId: Principal;
    name: string;
    startDate: Timestamp;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface MonthlyBreakdown {
    month: bigint;
    totalDeltaE8s: bigint;
    year: bigint;
    readingCount: bigint;
    momDeltaE8s: bigint;
}
export interface InviteCode {
    status: InviteCodeStatus;
    code: string;
    createdAt: Timestamp;
}
export interface WtnStats {
    percentReturn: number;
    totalCapitalContributed: number;
    totalEarned: number;
    positionId: WtnPositionId;
    redeemableIcpValue: number;
    totalWithdrawn: number;
}
export type TimerId = bigint;
export interface WtnSnapshot {
    date: Timestamp;
    positionId: WtnPositionId;
    redeemableIcpValue: number;
    nicpHeld: number;
    eventType: WtnEventType;
    totalIcpPaid: number;
}
export type E8s = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface PriceSnapshot {
    pln: number;
    usd: number;
    timestamp: bigint;
    cached: boolean;
    unavailable: boolean;
}
export interface SyncResult {
    status: SyncStatus;
    maturityE8s?: bigint;
    lastSyncError?: string;
    stakedE8s?: bigint;
    neuronId: NeuronId;
}
export interface Cell {
    value: Value;
    name: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface NeuronStats {
    averageDailyRewardE8s: bigint;
    totalRewardsE8s: bigint;
    totalCapitalContributedE8s: E8s;
    currentMaturityE8s: bigint;
    apy30d: number;
    percentageReturn: number;
    neuronId: NeuronId;
    monthly: Array<MonthlyBreakdown>;
    totalDisbursedE8s: bigint;
    overallReturnPct: number;
}
export type DeltaE8s = bigint;
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface WtnHistoricalEntry {
    date: Timestamp;
    redeemableIcpValue: number;
    nicpHeld: number;
    totalIcpPaid: number;
}
export interface HistoricalEntry {
    stakedMaturityE8s: E8s;
    unstakedMaturityE8s: E8s;
    timestamp: Timestamp;
}
export interface DailyReward {
    stakedMaturityE8s: E8s;
    unstakedMaturityE8s: E8s;
    stakeDeltaE8s: E8s;
    autoStakeMaturity: boolean;
    timestamp: Timestamp;
    neuronId: NeuronId;
    deltaE8s: DeltaE8s;
    eventType: EventType;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface Neuron {
    id: NeuronId;
    dissolveDelaySeconds: bigint;
    ownerId: Principal;
    name: string;
    stakedE8s: E8s;
    initialStakeE8s: E8s;
    startDate: Timestamp;
}
export interface PortfolioStats {
    wtnRewardsThisMonthFloat: number;
    totalPortfolioValueE8s: bigint;
    totalMaturityE8s: bigint;
    wtnRewardsE8s: bigint;
    nnsStakedE8s: E8s;
    totalRewardsThisMonthE8s: bigint;
    wtnCapitalContributedE8s: E8s;
    totalRewardsE8s: bigint;
    combinedRewardsThisMonthE8s: bigint;
    blendedApy: number;
    totalStakedE8s: E8s;
    nnsRewardsThisMonthE8s: bigint;
    totalCapitalContributedE8s: E8s;
    percentageReturn: number;
    nnsCapitalContributedE8s: E8s;
    nnsRewardsE8s: bigint;
    wtnStakedE8s: E8s;
    totalDisbursedE8s: bigint;
    neuronCount: bigint;
}
export type NeuronId = bigint;
export interface PortfolioRewardStats {
    monthlyReadings: bigint;
    averageDailyRewardE8s: bigint;
    totalRewardsE8s: bigint;
    totalCapitalContributedE8s: E8s;
    apy30d: number;
    monthly: Array<MonthlyBreakdown>;
    overallReturnPct: number;
}
export type WtnPositionId = bigint;
export enum EventType {
    mergedToStake = "mergedToStake",
    normalGrowth = "normalGrowth",
    firstReading = "firstReading",
    externalTopUp = "externalTopUp",
    disburseOrSpawn = "disburseOrSpawn"
}
export enum InviteCodeStatus {
    revoked = "revoked",
    used = "used",
    unused = "unused"
}
export enum SyncStatus {
    hotkeyRequired = "hotkeyRequired",
    neverSynced = "neverSynced",
    failed = "failed",
    synced = "synced"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WtnEventType {
    firstReading = "firstReading",
    capitalAdded = "capitalAdded",
    withdrawal = "withdrawal",
    organicGrowth = "organicGrowth"
}
export interface backendInterface {
    ___dailySyncInstalled(): Promise<boolean>;
    __accessControlState(): Promise<any>;
    __adminPrincipal(): Promise<any>;
    __grantedPrincipals(ko: Principal | null, count: bigint | null): Promise<Array<Principal>>;
    __inviteCodes(): Promise<any>;
    __neurons(): Promise<any>;
    __nextWtnPositionId(): Promise<any>;
    __priceCache(): Promise<any>;
    __rewards(): Promise<any>;
    __syncErrors(): Promise<any>;
    __syncStatuses(): Promise<any>;
    __wtnPositions(ko: WtnPositionId | null, count: bigint | null): Promise<Array<[WtnPositionId, WtnPosition]>>;
    __wtnSnapshots(): Promise<any>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addNeuron(id: NeuronId, name: string, startDate: bigint, dissolveDelaySeconds: bigint, initialStakeE8s: bigint): Promise<void>;
    addWtnPosition(name: string, startDate: bigint): Promise<WtnPosition>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkAccess(code: string): Promise<boolean>;
    deleteSnapshot(neuronId: NeuronId, timestamp: bigint): Promise<void>;
    deleteWtnSnapshot(positionId: WtnPositionId, date: bigint): Promise<void>;
    editSnapshot(neuronId: NeuronId, timestamp: bigint, newTimestamp: bigint, newMaturityE8s: bigint): Promise<void>;
    editWtnSnapshot(positionId: WtnPositionId, date: bigint, newDate: bigint, newNicpHeld: number, newTotalIcpPaid: number, newRedeemableIcpValue: number): Promise<void>;
    execute(qJson: string): Promise<Result>;
    generateInviteCode(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentIcpPrice(): Promise<PriceSnapshot>;
    getHistoricalIcpPrice(date: string): Promise<PriceSnapshot>;
    getNeuronStats(neuronId: NeuronId): Promise<NeuronStats>;
    getPortfolioRewardStats(): Promise<PortfolioRewardStats>;
    getTodayRewardE8s(dayStartNs: bigint, dayEndNs: bigint): Promise<bigint>;
    getPortfolioStats(): Promise<PortfolioStats>;
    getRewardHistory(neuronId: NeuronId): Promise<Array<DailyReward>>;
    getSyncError(neuronId: NeuronId): Promise<string | null>;
    getSyncStatus(neuronId: NeuronId): Promise<SyncStatus>;
    getWtnPosition(positionId: WtnPositionId): Promise<WtnPosition | null>;
    getWtnSnapshots(positionId: WtnPositionId): Promise<Array<WtnSnapshot>>;
    getWtnStats(positionId: WtnPositionId): Promise<WtnStats>;
    importHistoricalData(neuronId: NeuronId, entries: Array<HistoricalEntry>): Promise<void>;
    importWtnHistoricalData(positionId: WtnPositionId, entries: Array<WtnHistoricalEntry>): Promise<void>;
    isAdminBootstrapped(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerAdminPrincipal(): Promise<boolean>;
    isCallerGranted(): Promise<boolean>;
    isPrincipalGranted(principal: Principal): Promise<boolean>;
    listInviteCodes(): Promise<Array<InviteCode>>;
    listMyNeurons(): Promise<Array<Neuron>>;
    listMyWtnPositions(): Promise<Array<WtnPosition>>;
    recordSnapshot(neuronId: NeuronId, unstakedMaturityE8s: bigint, stakedMaturityE8s: bigint, autoStakeMaturity: boolean, timestamp: bigint, externalTopUpE8s: bigint): Promise<DailyReward>;
    recordWtnSnapshot(positionId: WtnPositionId, date: bigint, nicpHeld: number, totalIcpPaid: number, redeemableIcpValue: number): Promise<WtnSnapshot>;
    removeNeuron(neuronId: NeuronId): Promise<void>;
    removeWtnPosition(positionId: WtnPositionId): Promise<void>;
    revokeInviteCode(code: string): Promise<void>;
    /**
     * / Schedule the next daily sync at 18:01 Europe/Warsaw. Recomputes the
     * / target on every call so DST transitions do not cause drift. After the
     * / sync runs, reschedules for the following 18:01 Warsaw.
     * /
     * / `Timer.setTimer<system>` requires the `<system>` capability, which is
     * / available in `shared` functions and async callbacks but NOT in a plain
     * / actor `func` or a transient-let initializer. This function is therefore
     * / only ever called from two system-capable contexts: (1) the
     * / `public shared func startDailySync()` below, and (2) the async timer
     * / callback passed to `Timer.setTimer` (which itself has the system
     * / capability, so rescheduling works). It must NOT be called from a plain
     * / transient let or a non-shared private func.
     */
    scheduleNextSync(): Promise<TimerId>;
    schema(): Promise<string>;
    setAdminPrincipal(): Promise<void>;
    /**
     * / Install the daily sync timer on first call. Public shared functions run
     * / in an async context that has the `<system>` capability, so
     * / `scheduleNextSync()` (which calls `Timer.setTimer<system>`) is valid
     * / here. Idempotent: subsequent calls are no-ops once the timer is running
     * / (the timer reschedules itself from its own async callback, which also
     * / has the system capability).
     */
    startDailySync(): Promise<void>;
    syncAllMyNeurons(): Promise<Array<SyncResult>>;
    syncNeuron(neuronId: NeuronId): Promise<SyncResult>;
    /**
     * / IC HTTP outcall transform callback. Required by the IC HTTP outcall
     * / protocol: it must be a public `query` function on the actor and strips
     * / response headers so the response body is the only thing that survives
     * / into consensus. Passed to PricesLib functions and the PricesApi mixin.
     */
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateNeuron(neuron: Neuron): Promise<void>;
    updateWtnPosition(position: WtnPosition): Promise<void>;
}
import type { Cell as _Cell, DailyReward as _DailyReward, DeltaE8s as _DeltaE8s, E8s as _E8s, Error as _Error, EventType as _EventType, InviteCode as _InviteCode, InviteCodeStatus as _InviteCodeStatus, NeuronId as _NeuronId, Result as _Result, Result__1 as _Result__1, SyncResult as _SyncResult, SyncStatus as _SyncStatus, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value, WtnEventType as _WtnEventType, WtnPosition as _WtnPosition, WtnPositionId as _WtnPositionId, WtnSnapshot as _WtnSnapshot } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async ___dailySyncInstalled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.___dailySyncInstalled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.___dailySyncInstalled();
            return result;
        }
    }
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __adminPrincipal(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__adminPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__adminPrincipal();
            return result;
        }
    }
    async __grantedPrincipals(arg0: Principal | null, arg1: bigint | null): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.__grantedPrincipals(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__grantedPrincipals(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __inviteCodes(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__inviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__inviteCodes();
            return result;
        }
    }
    async __neurons(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__neurons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__neurons();
            return result;
        }
    }
    async __nextWtnPositionId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextWtnPositionId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextWtnPositionId();
            return result;
        }
    }
    async __priceCache(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__priceCache();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__priceCache();
            return result;
        }
    }
    async __rewards(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__rewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__rewards();
            return result;
        }
    }
    async __syncErrors(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__syncErrors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__syncErrors();
            return result;
        }
    }
    async __syncStatuses(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__syncStatuses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__syncStatuses();
            return result;
        }
    }
    async __wtnPositions(arg0: WtnPositionId | null, arg1: bigint | null): Promise<Array<[WtnPositionId, WtnPosition]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__wtnPositions(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__wtnPositions(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __wtnSnapshots(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__wtnSnapshots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__wtnSnapshots();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addNeuron(arg0: NeuronId, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNeuron(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNeuron(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addWtnPosition(arg0: string, arg1: bigint): Promise<WtnPosition> {
        if (this.processError) {
            try {
                const result = await this.actor.addWtnPosition(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWtnPosition(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkAccess(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAccess(arg0);
            return result;
        }
    }
    async deleteSnapshot(arg0: NeuronId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSnapshot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSnapshot(arg0, arg1);
            return result;
        }
    }
    async deleteWtnSnapshot(arg0: WtnPositionId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWtnSnapshot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWtnSnapshot(arg0, arg1);
            return result;
        }
    }
    async editSnapshot(arg0: NeuronId, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editSnapshot(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editSnapshot(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async editWtnSnapshot(arg0: WtnPositionId, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editWtnSnapshot(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editWtnSnapshot(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentIcpPrice(): Promise<PriceSnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentIcpPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentIcpPrice();
            return result;
        }
    }
    async getHistoricalIcpPrice(arg0: string): Promise<PriceSnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoricalIcpPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoricalIcpPrice(arg0);
            return result;
        }
    }
    async getNeuronStats(arg0: NeuronId): Promise<NeuronStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getNeuronStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNeuronStats(arg0);
            return result;
        }
    }
    async getPortfolioRewardStats(): Promise<PortfolioRewardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioRewardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioRewardStats();
            return result;
        }
    }
    async getTodayRewardE8s(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayRewardE8s(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayRewardE8s(arg0, arg1);
            return result;
        }
    }
    async getPortfolioStats(): Promise<PortfolioStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioStats();
            return result;
        }
    }
    async getRewardHistory(arg0: NeuronId): Promise<Array<DailyReward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewardHistory(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewardHistory(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSyncError(arg0: NeuronId): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSyncError(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSyncError(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSyncStatus(arg0: NeuronId): Promise<SyncStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getSyncStatus(arg0);
                return from_candid_SyncStatus_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSyncStatus(arg0);
            return from_candid_SyncStatus_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWtnPosition(arg0: WtnPositionId): Promise<WtnPosition | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWtnPosition(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWtnPosition(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWtnSnapshots(arg0: WtnPositionId): Promise<Array<WtnSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWtnSnapshots(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWtnSnapshots(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWtnStats(arg0: WtnPositionId): Promise<WtnStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getWtnStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWtnStats(arg0);
            return result;
        }
    }
    async importHistoricalData(arg0: NeuronId, arg1: Array<HistoricalEntry>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importHistoricalData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importHistoricalData(arg0, arg1);
            return result;
        }
    }
    async importWtnHistoricalData(arg0: WtnPositionId, arg1: Array<WtnHistoricalEntry>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importWtnHistoricalData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importWtnHistoricalData(arg0, arg1);
            return result;
        }
    }
    async isAdminBootstrapped(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminBootstrapped();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminBootstrapped();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerAdminPrincipal(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdminPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdminPrincipal();
            return result;
        }
    }
    async isCallerGranted(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerGranted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerGranted();
            return result;
        }
    }
    async isPrincipalGranted(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPrincipalGranted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPrincipalGranted(arg0);
            return result;
        }
    }
    async listInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInviteCodes();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInviteCodes();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyNeurons(): Promise<Array<Neuron>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyNeurons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyNeurons();
            return result;
        }
    }
    async listMyWtnPositions(): Promise<Array<WtnPosition>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyWtnPositions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyWtnPositions();
            return result;
        }
    }
    async recordSnapshot(arg0: NeuronId, arg1: bigint, arg2: bigint, arg3: boolean, arg4: bigint, arg5: bigint): Promise<DailyReward> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSnapshot(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_DailyReward_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSnapshot(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_DailyReward_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordWtnSnapshot(arg0: WtnPositionId, arg1: bigint, arg2: number, arg3: number, arg4: number): Promise<WtnSnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.recordWtnSnapshot(arg0, arg1, arg2, arg3, arg4);
                return from_candid_WtnSnapshot_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordWtnSnapshot(arg0, arg1, arg2, arg3, arg4);
            return from_candid_WtnSnapshot_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeNeuron(arg0: NeuronId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeNeuron(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeNeuron(arg0);
            return result;
        }
    }
    async removeWtnPosition(arg0: WtnPositionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWtnPosition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWtnPosition(arg0);
            return result;
        }
    }
    async revokeInviteCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeInviteCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeInviteCode(arg0);
            return result;
        }
    }
    async scheduleNextSync(): Promise<TimerId> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleNextSync();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleNextSync();
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setAdminPrincipal(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminPrincipal();
            return result;
        }
    }
    async startDailySync(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startDailySync();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startDailySync();
            return result;
        }
    }
    async syncAllMyNeurons(): Promise<Array<SyncResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.syncAllMyNeurons();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.syncAllMyNeurons();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async syncNeuron(arg0: NeuronId): Promise<SyncResult> {
        if (this.processError) {
            try {
                const result = await this.actor.syncNeuron(arg0);
                return from_candid_SyncResult_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.syncNeuron(arg0);
            return from_candid_SyncResult_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateNeuron(arg0: Neuron): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNeuron(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNeuron(arg0);
            return result;
        }
    }
    async updateWtnPosition(arg0: WtnPosition): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWtnPosition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWtnPosition(arg0);
            return result;
        }
    }
}
function from_candid_Cell_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_DailyReward_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyReward): DailyReward {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_EventType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_InviteCodeStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InviteCodeStatus): InviteCodeStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_InviteCode_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InviteCode): InviteCode {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_SyncResult_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SyncResult): SyncResult {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_SyncStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SyncStatus): SyncStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_WtnEventType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WtnEventType): WtnEventType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_WtnSnapshot_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WtnSnapshot): WtnSnapshot {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WtnPosition]): WtnPosition | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n12(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n16(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stakedMaturityE8s: _E8s;
    unstakedMaturityE8s: _E8s;
    stakeDeltaE8s: _E8s;
    autoStakeMaturity: boolean;
    timestamp: _Timestamp;
    neuronId: _NeuronId;
    deltaE8s: _DeltaE8s;
    eventType: _EventType;
}): {
    stakedMaturityE8s: E8s;
    unstakedMaturityE8s: E8s;
    stakeDeltaE8s: E8s;
    autoStakeMaturity: boolean;
    timestamp: Timestamp;
    neuronId: NeuronId;
    deltaE8s: DeltaE8s;
    eventType: EventType;
} {
    return {
        stakedMaturityE8s: value.stakedMaturityE8s,
        unstakedMaturityE8s: value.unstakedMaturityE8s,
        stakeDeltaE8s: value.stakeDeltaE8s,
        autoStakeMaturity: value.autoStakeMaturity,
        timestamp: value.timestamp,
        neuronId: value.neuronId,
        deltaE8s: value.deltaE8s,
        eventType: from_candid_EventType_n23(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: _Timestamp;
    positionId: _WtnPositionId;
    redeemableIcpValue: number;
    nicpHeld: number;
    eventType: _WtnEventType;
    totalIcpPaid: number;
}): {
    date: Timestamp;
    positionId: WtnPositionId;
    redeemableIcpValue: number;
    nicpHeld: number;
    eventType: WtnEventType;
    totalIcpPaid: number;
} {
    return {
        date: value.date,
        positionId: value.positionId,
        redeemableIcpValue: value.redeemableIcpValue,
        nicpHeld: value.nicpHeld,
        eventType: from_candid_WtnEventType_n32(_uploadFile, _downloadFile, value.eventType),
        totalIcpPaid: value.totalIcpPaid
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _InviteCodeStatus;
    code: string;
    createdAt: _Timestamp;
}): {
    status: InviteCodeStatus;
    code: string;
    createdAt: Timestamp;
} {
    return {
        status: from_candid_InviteCodeStatus_n37(_uploadFile, _downloadFile, value.status),
        code: value.code,
        createdAt: value.createdAt
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SyncStatus;
    maturityE8s: [] | [bigint];
    lastSyncError: [] | [string];
    stakedE8s: [] | [bigint];
    neuronId: _NeuronId;
}): {
    status: SyncStatus;
    maturityE8s?: bigint;
    lastSyncError?: string;
    stakedE8s?: bigint;
    neuronId: NeuronId;
} {
    return {
        status: from_candid_SyncStatus_n26(_uploadFile, _downloadFile, value.status),
        maturityE8s: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.maturityE8s)),
        lastSyncError: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.lastSyncError)),
        stakedE8s: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.stakedE8s)),
        neuronId: value.neuronId
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mergedToStake: null;
} | {
    normalGrowth: null;
} | {
    firstReading: null;
} | {
    externalTopUp: null;
} | {
    disburseOrSpawn: null;
}): EventType {
    return "mergedToStake" in value ? EventType.mergedToStake : "normalGrowth" in value ? EventType.normalGrowth : "firstReading" in value ? EventType.firstReading : "externalTopUp" in value ? EventType.externalTopUp : "disburseOrSpawn" in value ? EventType.disburseOrSpawn : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hotkeyRequired: null;
} | {
    neverSynced: null;
} | {
    failed: null;
} | {
    synced: null;
}): SyncStatus {
    return "hotkeyRequired" in value ? SyncStatus.hotkeyRequired : "neverSynced" in value ? SyncStatus.neverSynced : "failed" in value ? SyncStatus.failed : "synced" in value ? SyncStatus.synced : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    firstReading: null;
} | {
    capitalAdded: null;
} | {
    withdrawal: null;
} | {
    organicGrowth: null;
}): WtnEventType {
    return "firstReading" in value ? WtnEventType.firstReading : "capitalAdded" in value ? WtnEventType.capitalAdded : "withdrawal" in value ? WtnEventType.withdrawal : "organicGrowth" in value ? WtnEventType.organicGrowth : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    revoked: null;
} | {
    used: null;
} | {
    unused: null;
}): InviteCodeStatus {
    return "revoked" in value ? InviteCodeStatus.revoked : "used" in value ? InviteCodeStatus.used : "unused" in value ? InviteCodeStatus.unused : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n6(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyReward>): Array<DailyReward> {
    return value.map((x)=>from_candid_DailyReward_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WtnSnapshot>): Array<WtnSnapshot> {
    return value.map((x)=>from_candid_WtnSnapshot_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InviteCode>): Array<InviteCode> {
    return value.map((x)=>from_candid_InviteCode_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SyncResult>): Array<SyncResult> {
    return value.map((x)=>from_candid_SyncResult_n40(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WtnPositionId | null): [] | [_WtnPositionId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
